/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SvgTo3dMesh {
        "backgroundColor": string;
        "color": string;
        "explodeInDuration": number;
        "explodeOutDuration": number;
        "height": number;
        "opacity": number;
        "scaleDownDuration": number;
        "scaleUpDuration": number;
        "svgs": string[];
    }
}
declare global {
    interface HTMLSvgTo3dMeshElement extends Components.SvgTo3dMesh, HTMLStencilElement {
    }
    var HTMLSvgTo3dMeshElement: {
        prototype: HTMLSvgTo3dMeshElement;
        new (): HTMLSvgTo3dMeshElement;
    };
    interface HTMLElementTagNameMap {
        "svg-to-3d-mesh": HTMLSvgTo3dMeshElement;
    }
}
declare namespace LocalJSX {
    interface SvgTo3dMesh {
        "backgroundColor"?: string;
        "color"?: string;
        "explodeInDuration"?: number;
        "explodeOutDuration"?: number;
        "height"?: number;
        "opacity"?: number;
        "scaleDownDuration"?: number;
        "scaleUpDuration"?: number;
        "svgs"?: string[];
    }
    interface IntrinsicElements {
        "svg-to-3d-mesh": SvgTo3dMesh;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "svg-to-3d-mesh": LocalJSX.SvgTo3dMesh & JSXBase.HTMLAttributes<HTMLSvgTo3dMeshElement>;
        }
    }
}
